### ISSUE TITLE
Request to allow installation via NPM package

### ISSUE THREAD

**Issue by cyfrost** [Xon/Choices.js#1]
**Is your feature request related to a problem? Please describe.**
First off, thanks a lot for maintaining this fork with much needed improvements. Currently there's no NPM package to install this fork which is an issue for users hoping to use this package.

**Describe the solution you'd like**
 I'm hoping to have this package on hosted on NPM for easier installation for users.

**Describe alternatives you've considered**
While I've contemplated getting this fork's improvements back upstream (which would be great for everyone), upstream seems largely unmaintained. Thus, I'm not entirely sure what other feasible alternatives exist at this point.

**Additional context**
None

**Comment by Xon** [comment]
I'm still making breaking changes and I don't feel it is quite ready for release yet.  I'm still working on updating/replacing the end-to-end testing framework rather than 3 variations the project had before.

I can merge requests in the upstream repo (but no my own PR's) so I'm hopeful I'll be able todo some maintenance once things are in shape. You can see the open PR https://github.com/Choices-js/Choices/pull/1166 for merging it upstream.

**Comment by cyfrost** [comment]
Thanks for the response @Xon, sounds good. Hoping v11 will be great release! Cheers
