### ISSUE TITLE
Press enter with addChoices: true submits form

### ISSUE THREAD

**Issue by creativetags** [Xon/Choices.js#2]
I've been testing your new option for adding a custom choice, thanks for working on this. When I type something to add and press enter as instructed it instantly submits the form which was not what I wanted. It's doing that with singleModeForMultiSelect set to true or false. I'm using select-one.

**Comment by Xon** [comment]
That _should_ be fixed with latest `main`

There is a `select-one` e2e test to check for form-submit which is passing. I haven't confirmed that is working for `select-multiple` as I'm still getting the e2e tests updated & working.

Once the tests are stable, I'll create a tagged `v11.0.0-rc7` release on this repo.

**Comment by Xon** [comment]
Running the tests locally works fine, but the github actions refuses to start the webserver needed todo the tests. That isn't relevant for [v11.0.0-rc7](https://github.com/Xon/Choices.js/releases/tag/v11.0.0-rc7) so I've created a tagged release for that.
